export enum actionTypes {
    FETCHREQUEST = "FETCH_REQUEST",
    FETCHTSUCESS = "FETCH_SUCCESS",
    FETCHTFAILURE = "FETCH_FAILURE",

    SET_PRODUCTS = "SET_PRODUCTS",
    SELECTED_PRODUCT = "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT"
}

